version: '3.9'
services:
  app:
    container_name: golang_container
    environment:
      - PG_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PG_DATABASE=${DB_NAME}
      - PG_HOSTNAME=${DB_HOST}
      - PG_PORT=${DB_PORT}
    tty: true
    build: .
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - learning

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '1234:5432'
    networks:
      - learning

# Networks to be created to facilitate communication between containers
networks:
  learning:
    driver: bridge
