basePath: /
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is an API server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Swagger API
  version: "2.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /partners/{id}:
    get:
      consumes:
      - '*/*'
      description: Returns partners data for an id as integer.
      parameters:
      - description: Partner ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get partners data for a given id.
      tags:
      - partners
  /query/{id}:
    get:
      consumes:
      - '*/*'
      description: Returns list of partners that satisfy given query.
      parameters:
      - description: Phone number for contact
        example: "01604323444"
        in: query
        name: phone
        type: string
      - description: 'Address in format: Latitude,Longitude'
        example: 40.076763,113.30013
        in: query
        name: address
        required: true
        type: string
      - collectionFormat: csv
        description: 'Material collection: carpet,tiles,wood'
        example: carpet,tiles,wood
        in: query
        items:
          type: string
        name: material
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get list of partners that satisfy given query.
      tags:
      - query
schemes:
- http
swagger: "2.0"
